name: singularity-docs

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create conda environment
        run: conda create --quiet -c conda-forge --name shpc spython

      - name: Install shpc
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate shpc
          pip install -e .

      - name: Generate docs
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate shpc
          root=$PWD
          # clone the github pages branch
          cd /opt
          git clone -b gh-pages https://github.com/singularityhub/singularity-hpc
          cd singularity-hpc
          /bin/bash generate.sh
          cd $root
          
      - name: Push to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printf "GitHub Actor: ${GITHUB_ACTOR}\n"

          cd $root
          mv /opt/singularity-hpc/.git .git 

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

          git checkout gh-pages
          rm -rf _library      
          mv /opt/singularity-hpc/_library _library          
          git add _library/*
          ls
          cat .git/config
          set +e
          git status | grep modified
          if [ $? -eq 0 ]; then
              set -e
              printf "Changes\n"
              git commit -m "Automated push to update GitHub pages $(date '+%Y-%m-%d')" || exit 0
              git push origin gh-pages
          else
              set -e
              printf "No changes\n"
          fi
